FROM arm32v7/ubuntu
# See: https://lobradov.github.io/Building-docker-multiarch-images
# Build via: sudo docker build -f Dockerfile.arm32v7 --tag richardbronosky/latex-compiler .

MAINTAINER Bruno Bronosky <bruno@bronosky.com>

RUN apt-get update

RUN apt-get install -y file texlive-latex-recommended

ADD latexcat /usr/local/bin/latexcat
RUN chmod a+x /usr/local/bin/latexcat

VOLUME /work

ENTRYPOINT ["/usr/local/bin/latexcat"]
