#!/usr/bin/env bash

generate() {
    if [[ $sourcefile =~ \.tex$ ]]; then
        echo "[INFO] Launching pdflatex $sourcefile.">>latexcat.log
        # generate PDF capturing stdout and stderr in a log file
        pdflatex --interaction=nonstopmode $sourcefile &>>latexcat.log
    else
        echo "[INFO] Launching tex $sourcefile.">>latexcat.log
        tex $sourcefile >>latexcat.log
    fi
}

# make and enter a temporary directory
cd $(mktemp -d)
mkdir output
cd output

# write stdin to a file
cat /dev/stdin > ../sourcefile

# determine the type of the source file
if file -b ../sourcefile | grep -q "tar archive"; then
    echo "[INFO] Detected tar sourcefile.">>latexcat.log
    tarfile=1
    tar xf ../sourcefile
    # find the latex file
    for sourcefile in $(ls -1 2>/dev/null | grep -vE '.tex$'); do
        generate
    done
    for sourcefile in $(ls -1 *.tex 2>/dev/null); do
        generate
    done
else
    echo "[INFO] Detected single sourcefile.">>latexcat.log
    sourcefile="../sourcefile"
    generate
fi

if [[ -n $tarfile ]]; then
    # remove the source files
    tar tf ../sourcefile | xargs -n 1 rm
    # check for more than 1 pdf
    if [[ $(ls -1 *.pdf | wc -l) -gt 1 ]] && [[ $1 != "--debug" ]]; then
        echo "[INFO] Detected need for tar output.">>latexcat.log
        echo "[INFO] Requesting tar output.">>latexcat.log
        # force tar ouput
        set -- "--tar"
    fi
fi

# send log to stdout
if [[ $1 == "--debug" ]]; then
    echo "[INFO] Detected debug.">>latexcat.log
    echo "[INFO] Sending latexcat.log.">>latexcat.log
    cat latexcat.log
    echo;
    ls -l;
# send tar to stdout
elif [[ $1 == "--tar" ]]; then
    echo "[INFO] Detected request for tar output.">>latexcat.log
    echo "[INFO] Sending tar output.">>latexcat.log
    cd ..
    tar cf - output
# send PDF to stdout
else
    cat *.pdf
fi
